services:
  - type: web
    name: mental-health-chatbot
    env: python
    plan: free  # You can upgrade to paid plans later
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python setup_nltk.py
    startCommand: |
      python app.py
    envVars:
      # PORT is automatically set by Render for web services
      - key: ENCRYPTION_KEY
        sync: false  # Set this in Render dashboard
      - key: HF_API_KEY
        sync: false  # Set this in Render dashboard  
      - key: OPENAI_API_KEY
        sync: false  # Set this in Render dashboard
      - key: GEMINI_API_KEY
        sync: false  # Set this in Render dashboard
      - key: SESSION_EXPIRY_MINUTES
        value: 30
      - key: MAX_CONVERSATION_LENGTH
        value: 100
      - key: CONTEXT_WINDOW
        value: 10
      - key: TOKEN_EXPIRY_HOURS
        value: 24
      - key: SECURE_COOKIES
        value: TRUE
      - key: PREFER_GEMINI
        value: TRUE
      - key: USE_OPENAI_FALLBACK
        value: TRUE